services:
  backend: # サービス名
    container_name: backend # コンテナ名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    volumes: # マウントディレクトリ
      - ./backend:/go/src/backend
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./build/.go_.env
    environment:
      - TZ=Asia/Tokyo
